### ISSUE TITLE
transfer to purescript-web

### ISSUE THREAD

**Issue by gbagan** [purescript-web/purescript-web-workers#1]
This is a proposal to transfer this repo to purescript-web.
@JordanMartinez

**Comment by JordanMartinez** [comment]
Thanks for the ping.

Here's what I think is correct:
- Web.Worker.Location (i.e. [WorkerLocation](https://html.spec.whatwg.org/multipage/workers.html#worker-locations))
- Web.Worker.MessagePort (i.e. [MessagesPort](https://html.spec.whatwg.org/multipage/web-messaging.html#messageport))

Here's what I think is incorrect or has missing functionality:
- Web.Worker.GlobalScope (i.e. [WorkerGlobalScope](https://html.spec.whatwg.org/multipage/workers.html#the-workerglobalscope-common-interface)). These functions are missing:
  - [onlanguagechange](https://html.spec.whatwg.org/multipage/workers.html#handler-workerglobalscope-onlanguagechange);
  - [onoffline](https://html.spec.whatwg.org/multipage/workers.html#handler-workerglobalscope-onoffline);
  - [ononline](https://html.spec.whatwg.org/multipage/workers.html#handler-workerglobalscope-ononline);
  - [onrejectionhandled](https://html.spec.whatwg.org/multipage/workers.html#handler-workerglobalscope-onrejectionhandled);
  - [onunhandledrejection](https://html.spec.whatwg.org/multipage/workers.html#handler-workerglobalscope-onunhandledrejection);
  - [importScripts](https://html.spec.whatwg.org/multipage/workers.html#dom-workerglobalscope-importscripts)
- Web.Worker.MessageEvent (i.e. [MessageEvent](https://html.spec.whatwg.org/multipage/comms.html#messageevent)):
  - the nullable `source` attribute, which is a [MessageEventSource](https://html.spec.whatwg.org/multipage/comms.html#messageeventsource)
- Web.Worker.Worker (i.e. [Worker](https://html.spec.whatwg.org/multipage/workers.html#dedicated-workers-and-the-worker-interface)):
  - "credentials is only used if [the WorkerType] is 'module'" (source: [WorkerOptions](https://html.spec.whatwg.org/multipage/workers.html#dedicated-workers-and-the-worker-interface)). We should account for that in our bindings to prevent someone from including credentials if they are using `Classic`. I think the easiest way would be to make `Module` take a `Credentials` argument.
  - where is `terminate`?
  - AFAICT, a `Worker` is a `DedicatedWorkerGlobalScope`
     - where is `close`?
- [Shared Worker](https://html.spec.whatwg.org/multipage/workers.html#shared-workers-and-the-sharedworker-interface)
   - Where are the bindings for `SharedWorker`?

I'm not sure about these things:
- Web.Worker.Navigator (i.e. [WorkerNavigator](https://html.spec.whatwg.org/multipage/workers.html#the-workernavigator-object))
    - the stuff from the [NavigatorID](https://html.spec.whatwg.org/multipage/system-state.html#client-identification) interface is missing. I'm not sure if this should be added, however, because they mostly return constants for privacy reasons.
    
Other than above, is there anything you think is problematic with the current bindings? Or things you think should be done a certain way but may not have time to do right now?

**Comment by JordanMartinez** [comment]
Also, I'd prefer that the FFI be written using `EffectFnX`, but I don't think that's a requirement to get this transferred.

**Comment by JordanMartinez** [comment]
> Unless I am wrong, close and terminate are implemented.

Ah, you're correct. Sorry about that.

Hmm... What advantages would there be in implementing it in a separate library? Won't it need to use some of the types defined here, which means it's harder to maintain due to the dependency? I'm not sure that makes sense.

**Comment by gbagan** [comment]
@JordanMartinez

I think I have adressed all your comments (except for WorkerNavigator).
Some remarks.

1) I have created two modules DedicatedWorkerGlobalScope and SharedWorkerGlobalScope.
Each of these modules imports and reexports functions in GlobalScope.

2) The classes Worker and SharedWorker inherit from AbstractWorker but, since the only method of AbstractWorker is onerror, I have duplicated the function onError in the module Worker and SharedWorker.

3) In general, MessageEventSource can be a MessagePort or a WindowProxy or a ServiceWorker.
But, in the context of (Shared) Workers, it can only be a MessagePort (or null).
So the function MessgeEvent.source returns a Maybe MessagePort.
Although it is not very generic, I think it prevents cross dependencies between different libraries

4) I have replaced bower.json with spago.dhall

**Comment by JordanMartinez** [comment]
I think this is good enough for a transfer. I'd still like to make a few changes, but that can be done once the transfer is done. Sound good?

**Comment by gbagan** [comment]
Thank you. Can I transfer the repo now or am I waiting for something?

**Comment by JordanMartinez** [comment]
Nah, let's transfer it. I'll clean it up once I get access to it.
