### ISSUE TITLE
The type of postMessage is too permissive

### ISSUE THREAD

**Issue by gbagan** [purescript-web/purescript-web-workers#2]
@JordanMartinez 

In the current implementation of web-workers, worker # [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage) a accepts any type for a.
But, in the documentation, it is said that the posted message must be serializable which is equivalent to be a correct input of
[structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#supported_types).
So I propose to implement a type class Serializable
and replace the signature of postMessage with 
```haskell
forall a. Serializable a => a -> Worker -> Effect Unit
```
@natefaubion said that it implemented something similar in
https://github.com/natefaubion/purescript-node-workerbees/blob/main/src/Node/WorkerBees.purs#L112-L150

**Comment by JordanMartinez** [comment]
Any reason why we don't just use `Sendable`?

**Comment by JordanMartinez** [comment]
I think we should call the class `IsSendable` because it's just a boolean check at the type-level. That will also make it differ from Nate's library's class name.

**Comment by gbagan** [comment]
I close this issue since it has been fixed.
